#!/bin/sh -ex

REPO="thingsboard/thingsboard"
GH_API="https://api.github.com/repos/$REPO/releases/latest"
LATEST=$(curl -s $GH_API | grep -oP '"tag_name": "\K(.*)(?=")')
VERSION=${LATEST#v}

FILENAME="thingsboard-$VERSION.deb"
GH_DL="https://github.com/$REPO/releases/download/v${VERSION}/${FILENAME}"
wget $GH_DL -O /usr/local/src/thingsboard.deb
