#!/bin/bash -e
# regenerate thingsboard pgsql password

. /etc/default/inithooks

CONF=/usr/share/thingsboard/conf/thingsboard.yml

PASSWORD=$(mcookie)
sed -i "\|SPRING_DATASOURCE_PASSWORD|s|D:.*|D:$PASSWORD}\"|" $CONF
$INITHOOKS_PATH/bin/pgsqlconf.py --user=thingsboard --pass="$PASSWORD"

