#!/bin/bash -e
# set thingsboard admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/thingsboard.py --pass="$APP_PASS" --email="$APP_EMAIL"

